### ISSUE TITLE
Problem with plugin and question what should I use as entry

### ISSUE THREAD

**Issue by EgoPingvina** [Jasmin2895/extension-build-webpack-plugin#10]
I have a question. What should I write in the entry? Chrome extension has a background.js and a content.js. And if I don't mistake, both of them are entry points.

My solution`s folder tree:
-Source
--locales
---en
----messages.json
--css
---content.css
---popup.css
--icons
---*some .png icons*
--js
---background.js
---content.js
--public
---javascript
----jquery-3.5.0.js
--manifest.json
--popup.html

I tried to do like this:

    const BrowserExtensionPlugin = require("extension-build-webpack-plugin");
    
    module.exports =
    {
        entry:
            {
                content     : './js/content',
                background  : './js/background'
            },
    
        output:
            {
                path        : __dirname + '/Source-result',
                filename    : '[name].js'
            },
    
        module:
        {
            rules:
            [
                {
                    test: /\.(js|jsx)$/,
                    use: 'babel-loader'
                }
            ]
        },
        
        plugins:
        [
            new BrowserExtensionPlugin(
                {
                    devMode: false,
                    name: "my-first-webpack.zip",
                    directory: "src",
                    updateType: "minor"
                })
        ]
    };

And take an error: "Error: Cannot find module '*path to main root folder*\node_modules\extension-build-webpack-plugin\index.js'. Please verify that the package.json has a valid "main" entry". I watched this path and found that index.js lies at "\node_modules\extension-build-webpack-plugin\src\index.js".

**Comment by Jasmin2895** [comment]
Hi @EgoPingvina ,

Ideally, you should mention the js file which you are using inside the script tag in your `.html` file. So it is the first js file that is called when your extension is loaded.

**Comment by EgoPingvina** [comment]
Ok, if I correctly understood you-I did entry filling correctly.
And what about trouble with index.js place from node modules?

**Comment by Jasmin2895** [comment]
Oh yes, there was an issue related to the path of the file. Fixed it!
An update is done for that fix.
Thanks for reporting. 😄

**Comment by EgoPingvina** [comment]
Thanks, now it works.
I am glad to help)
